name: 'StaticPages Upload'
description: 'Upload static HTML files to your self-hosted Static Pages instance'

inputs:
  apiUrl:
    description: 'The API endpoint of your Static Pages instance'
    required: true

  dir:
    description: 'The directory containing the static files to upload'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare API URL and fetch ID token
      id: prepare
      uses: actions/github-script@v7
      with:
        debug: false
        script: |
          let url = '${{ inputs.apiUrl }}';

          // Ensure it has a protocol
          if (!url.match(/^https?:\/\//)) {
            url = 'https://' + url;
          }

          // Remove trailing slashes
          url = url.replace(/\/+$/, '');

          // Append /upload if not present
          if (!url.endsWith('/upload')) {
            url += '/upload';
          }

          // Get GitHub-issued OIDC token
          const idToken = await core.getIDToken();

          core.setOutput('uploadApiEndpoint', url);
          core.setOutput('idtoken', idToken);

    - name: Upload static site artifacts
      shell: bash
      run: |
        set -euo pipefail

        URL="${{ steps.prepare.outputs.uploadApiEndpoint }}"
        IDTOKEN="${{ steps.prepare.outputs.idtoken }}"

        CURL_ARGS=()
        while IFS= read -r -d '' file; do
          relpath="${file#${{ inputs.dir }}}"
          CURL_ARGS+=("-F" "files[${relpath}]=@${file}")
        done < <(find "${{ inputs.dir }}" -type f -print0)

        echo "Uploading ${#CURL_ARGS[@]} files to $URL..."

        # Upload and capture HTTP status code and response body
        HTTP_STATUS=$(curl -s -w "%{http_code}" -o /tmp/response.out \
          -X POST "$URL" \
          -H "Authorization: Bearer $IDTOKEN" \
          "${CURL_ARGS[@]}")

        echo "HTTP status: $HTTP_STATUS"

        if [[ ! "$HTTP_STATUS" =~ ^2 ]]; then
          echo "Upload failed with status $HTTP_STATUS"
          echo "Response body:"
          cat /tmp/response.out
          exit 1
        fi
